# .github/workflows/ai-code-review.yml
name: “AI Code Review”

on:
  # keep your auto‑PR triggers if you still want them:
  # does this do anything at all?
  pull_request:
    types: [opened, synchronize, reopened]

  # add this to let you run it by hand
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'The PR number you want to review'
        required: true

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Determine PR number
        # pass it through from the dispatch input
        run: echo "PR_NUMBER=${{ github.event.inputs.pr_number }}" >> $GITHUB_ENV

      - name: Checkout PR merge ref
        uses: actions/checkout@v4
        with:
          # you can checkout the PR’s merge commit directly
          ref: refs/pull/${{ env.PR_NUMBER }}/merge

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install PyGithub openai

      - name: Run AI Review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python .github/scripts/auto_review.py --pr $PR_NUMBER
