# .github/workflows/auto-code-review.yml
name: “Auto Code Review”

# on:
#   pull_request:
#     types: [opened, synchronize, reopened]

on:
  workflow_run:
    workflows: ["CodeGen from Issue"]
    types: [completed]


permissions:
  pull-requests: write   # needed to post reviews/comments
  contents: read         # needed to checkout code

jobs:
  review:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 0      # full history so we can diff

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          pip install PyGithub openai

      - name: Run auto‑review and post comments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python .github/scripts/auto_review.py
